apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goo-backend-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: goo-backend
  endpoints:
  - port: "5000"
    path: "/metrics"
    interval: 15s
